### ISSUE TITLE
Synchronisierung Neuigkeiten > Rocket.Chat

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#10]
- [x] Diese Formatierung wird falsch synchronisiert: bei fett und kursiv gleichzeitig ein Wort wird Wort nur fett übertragen (fett+durchgestrichen, kursiv+durchgestrichen geht), Heading (wird nur „# Text“), normale Liste (wird nur „_ Text“), Bild im Text (wird nur „![](https…)) (bei Rocket.Chat gibt’s ja potenziell Möglichkeit, auch Bilder im Text anzuzeigen, müsste doch daher auch Synchronisierungsmöglichkeit geben?)
- [x] Wenn ich eine Neuigkeit nochmal in Projekt/Gruppe bearbeite, dann wird jedes Mal ein neuer Hinweis in Rocket.Chat generiert (siehe Screenshot), aber mir scheint nur max. 3x, bei jeder weiteren Bearbeitung kein neuer Link >
 Kann das auf nur einen Link reduziert werden?
- [x] Kurze Teaserzeile bei Link Neuigkeit im Rocket.Chat: Da wird der Rohtext mit Formatierungszeichen angezeigt (***Mal*** *ganze* **Formatierungen** ~~ausprobieren~~) > Diese Teaserzeile ist unnötig, da oben drüber richtige Neuigkeit steht; kann die herausgenommen werden?

![screenshot-8](https://user-images.githubusercontent.com/190013/63445664-140bac00-c439-11e9-9451-871ced0e71fd.png)
![screenshot-7](https://user-images.githubusercontent.com/190013/63445665-14a44280-c439-11e9-9c61-92811e6a6739.png)

**Comment by simonline** [comment]
Wenn möglich in Rocket.Chat Voransicht von Links ganz deaktivieren

**Comment by ghost** [comment]
Danke, das passt erstmal so mit den wichtigsten Sachen.

Noch zu verändern wäre, dass
- [x] 1) Bild im Text nicht gleich angezeigt wird, sondern nur als Link, (kannst du da etwas machen?) und dass
- [x] 2) Anhang nicht mit synchronisiert wird (würde ich aber begrüßen) - siehe hier Bild im Anhang, aber keine Synchronisierung im Kanal https://plattformn.staging.wechange.de/project/test-fur-rocketchat-4-future/note/test-neuigkeit-4-future-fur-ubertragung-dahsb/.

**Comment by simonline** [comment]
@michaelflohr
Zu 1) Leider erlaubt Rocket.Chat noch nicht, dass Bilder direkt im Text eingebettet werden. Aktuell wird im Text nur der Link angezeigt, die Bildvorschau erscheint dann bei meinem Test unter der Nachricht. Da kann ich leider nichts weiter machen.

Zu 2) Anhänge werden jetzt mit übertragen. Allerdings gibt es auch hier noch Mängel seitens Rocket.Chat: Beim Ändern von Nachrichten, wird der Anhang erneut hinzugefügt. Ich kann vorhandene Anhänge aktuell über die API weder Löschen noch Bearbeiten.

**Comment by ghost** [comment]
Ok.
2 ist nicht optimal, aber das stört erstmal nicht groß.
