### ISSUE TITLE
Rocket.Cat / WECHANGE-Bot

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#15]
Was passiert, wenn ich Benutzer „Rocket.Cat“ und „WECHANGE-Bot“ Direktnachrichten sende? Können die als Benutzer ausgeblendet werden?

**Comment by ghost** [comment]
WECHANGE-Bot wird in plattform-Bot, Rest bleibt

**Comment by simonline** [comment]
Auf Staging bleibt der Name bei WECHANGE-Bot, auf chat.plattform-n.org passen wir ihn dann an.
