### ISSUE TITLE
Beim Erstellen der Beschreibung des Testprojekts wird die erste Hälfte nicht formatiert, die zweite schon

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#2]
![screenshot](https://user-images.githubusercontent.com/190013/63444921-c9d5fb00-c437-11e9-8661-b87d92b0b15a.png)

**Comment by simonline** [comment]
Konnte ich so nicht reproduzieren. In jedem Fall hat das mit Rocket.Chat nichts zu tun, also bitte nochmals als neues Ticket für Sascha aufmachen.

**Comment by ghost** [comment]
Danke, dann schauen wir, wenn es auf live-Server vorkommen sollte.
