### ISSUE TITLE
Verlinkungsfehler

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#20]
Wenn ich in einer Benachrichtigungsmail auf „zur Nachricht“ klicke, dann verweist das z.B. in dem unteren Fall auf diesen Link https://chat.staging.wechange.de/channel/general => Da fehlt dann aber die obere plattform n-Registerzeile bei diesem Link und man ist praktisch nur bei Rocket.Chat, nicht auf der plattform n; gleiches passiert, wenn ich in Rocket.Chat bei einer Nachricht ganz rechts bei den drei Punkten auf „Link abrufen“ klicke  so entsteht Link, mit dem man auf die Diskussion zugreifen kann, aber da fehlt dann auch die obere plattform n-Zeile und nur so etwas entsteht hier: https://chat.staging.wechange.de/channel/general?msg=BRHYYQBju7AgJ42PS

**Comment by simonline** [comment]
Ich habe jetzt eine entsprechende Weiterleitung eingerichtet.

Hinweis: Wenn Benutzer*innen ein Browser-Plugin installiert haben, um den „HTTP-Referer“ zu unterbinden, funktioniert das bei diesen Benutzer*innen nicht.

**Comment by ghost** [comment]
Prima. Das Brower-Plugin werden vermutlich nur wenige IT-Expert_innen haben. Die wissen dann schon warum.
