### ISSUE TITLE
Rauminformation

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#24]
Die Beschreibung für „Rauminformation“ (siehe Screenshot) scheint der Name von Projekt/Gruppe zu sein. Darunter gibt es noch leere Felder Ankündigung und Thema. Es wirkt seltsam, dass die nicht mit Inhalt gefüllt werden können. Können die für alle automatisch von den Bots angelegten Kanäle einfach herausgenommen werden aus der Ansicht? Oder gibt es die Möglichkeit, dass die Admins von Projekt/Gruppe das bearbeiten dürfen?

![screenshot-14](https://user-images.githubusercontent.com/190013/63447363-2affcd80-c43c-11e9-8591-0b6afc357ccb.png)

**Comment by simonline** [comment]
Moderatoren-Rolle wird nicht richtig übernommen.

**Comment by simonline** [comment]
Rauminformationen können von Raum-Moderatoren bearbeitet werden. Raum-Moderatoren sind alle Projekt-/Gruppen-Admins. Da gab es vorher einen Bug, der jetzt behoben ist. Allerdings nur mit neuen Projekten/Gruppen.

**Comment by ghost** [comment]
Nachfrage @simonline : D.h. für alle nun mit der Umstellung automatisch angelegten schon bestehenden Projekte/Gruppen gibt es keine Möglichkeit, dass die Rauminformation bearbeitet werden kann? Das wäre sehr schade, da gerade Gruppen sehr stabil bei uns sind und nicht ständig aufgelöst und neu angelegt werden. Gibt es da noch eine Lösungsmöglichkeit, damit auch dort die Rauminformationen von Moderatoren bearbeitet werden können?

**Comment by simonline** [comment]
@michaelflohr Sorry, hab mich falsch ausgedrückt. Selbstverständlich geht das dann für die importierten Channels. Nur auf dem Staging geht das nicht für die alten.

**Comment by ghost** [comment]
Ok, prima.
