### ISSUE TITLE
Avatar Kanal Rocket.Chat = Avatar Projekt/Gruppe?

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#26]
Im Moment können Avatare von Projekten/Gruppen in Rocket.Chat nicht verändert werden. Wäre toll, wenn Avatar Projekt/Gruppe automatisch mit Rocket.Chat synchronisiert wird.

- [ ] #general: Bild übernehmen
- [ ] #news: Festes Bild (siehen Anhang)

**Comment by ghost** [comment]
bei #news festes Bild:  Durch z.B. ein Icon, was immer beim news-Kanal als Bild für den Kanal steht? (https://fontawesome.com/v4.7.0/icon/newspaper-o)
