### ISSUE TITLE
Automatischer Logout / Ungültiger Benutzer

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#3]
Zwischendurch automatischer Logout im Rocket.Chat-Fenster, während ich Testprojekt angelegt habe. Login ging dann auch automatisch wieder, zwischendurch kam aber rechts oben 3x die rote Anzeige „Ungültiger Benutzer“.

**Comment by tillman-berlin** [comment]
Auch werden Nutzer*innen automatisch abgemeldet, wenn eine Anmeldung über ein anderes Gerät/Desktopapp/Browser vorgenommen wird.
Besonders ist hier die Abmeldung von der App manchmal ein wenig anstregend, weil man sich so immer wieder auf dem Handy neu anmelden muss.
