### ISSUE TITLE
Direktnachrichten fehlen / fehlerhafte öffentliche Kanäle (z. B. 279-x-279)

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#30]
- [x] Woher kommen die (öffentlichen) Kanäle 279-x-279, 279-x-869, 869-x-279? Warum sind die so benannt? Was führt dazu, dass Kanäle als öffentlich oder privat importiert werden?
- [x] Dazu: Fehler Import Kommunikation nur zwischen Verena und mir
- [x] Von denen hier unten wurde z.B. nur „netzwerk n auf wachstumswende“ importiert als öffentlicher Kanal 869-x-279 (in der Anfangszeit der plattform n habe ich immer mal Verena da drüber geschrieben und sie mir; da fehlt alles, bis auf die 3 oberen öffentlichen Kanäle.
- [x] Kein Import von „Test für Import zu Rocket.Chat Fall 1“ und „Test für Import zu Rocket.Chat Fall 3“ (wichtig um Anhang-Import zu testen) nur an Verena adressiert: Die wurde nicht importiert, obwohl ich sie nur an Verena gesandt habe, die du ja auch importiert hast
- [x] Kein Import aller Direktnachrichten, die ich nur an Verena auf plattform n gesendet habe

**Comment by simonline** [comment]
@michaelflohr Jetzt sind deutlich mehr Direktnachrichten importiert worden. Bitte nochmals prüfen.

**Comment by ghost** [comment]
Passt jetzt alles, ok.
