### ISSUE TITLE
Nur Kommunikation zwischen Micha/Verena

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#31]
Wurden nur Kommunikationen von mir importiert, die an Verena adressiert waren, weil du sie auch importiert hast? Wenn nein, dann fehlen sehr viele Kommunikationen von mir? Bei Kommunikationen mit mehreren Personen, werden auch nur Verenas oder meine Antworten bestimmt aus dem genannten Grund importiert.

**Comment by simonline** [comment]
@michaelflohr Ja, nur die Kommunikation zwischen Verena und dir wurde importiert.

**Comment by ghost** [comment]
Jetzt sind alle Direktnachrichten von mir an Verena und umgekehrt da, prima!
