### ISSUE TITLE
Chat mit mehreren Personen: Zuordnung aller Personen

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#32]
Werden in importierten Kommunikationen mit mehreren Personen automatisch alle einem privaten Kanal zugeordnet? Ich sehe aber auf Testserver nur Mitglieder, die auch auf Testserver angemeldet sind?

Hier hast du Kommunikation mit Tillman importiert, aber Tillman ist nicht Mitglied im privaten Kanal – sicherlich, weil du Tillmans Nachrichten von plattform n nicht importiert hast? Wollte nur auf Nummer sicher gehen.

**Comment by simonline** [comment]
@michaelflohr Ganz genau, es wurden wie besprochen nur die Nachrichten von dir und Verena importiert.

**Comment by ghost** [comment]
Ok
