### ISSUE TITLE
Gruppennachricht: Antwort an Einzelperson

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#35]
Was passiert, wenn ich auf plattform n eine Nachricht an eine Gruppe/ein Projekt gesandt habe und dann z.B. wie im unteren Fall Verena nur an mich darauf antwortet? Hier auch Fehler: Meine Antwort an Verena (zugleich Test-Fall 5 „Test für Import zu Rocket.Chat Fall 5: Antworten auf frühere Nachrichten“) wurde nicht importiert.

**Comment by simonline** [comment]
@michaelflohr Hierfür wird dann eine Direktnachricht angelegt, Test-Fall 5 ist jetzt auch da.

**Comment by ghost** [comment]
Ok.
