### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#36]
Können in Kanal-Titel Umlaute wie ä, ü, ö, importiert werden? Bisher ist das nicht der Fall, was zu z.B. „Datenschutzerklarung“ führt. Ebenso bitte auch Import von Punkten, das passiert grad auch noch nicht, obwohl sowohl ä … und Punkte zulässig sind in Rocket.Chat für Kanal-Titel.

**Comment by simonline** [comment]
@michaelflohr Der Kanaltitel muss exakt dem Gruppen-Slug aus der plattform n entsprechen. Dort gibt es keine Umlaute, da diese historisch in nativen URLs nicht möglich waren.

**Comment by ghost** [comment]
Ok
