### ISSUE TITLE
Formatierungsfehler

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#37]
- [x] Kombination fett+kursiv: Wurde hier nicht korrekt übernommen als „netzwerk n“
- [x] Formatierungsfehler in Test-Fall 2: Der Formatierungsfehler bei Überschriften in Nachrichtentext war zu vermuten, dass z.B. #-Angaben nicht übernommen werden, da in Rocket.Chat keine Formatierungsfunktion integriert. Ich denke, stört nicht so und geht ja auch nicht anders. Dagegen wäre schön, wenn du nochmal bei den anderen Formatierungsfehlern im unteren Screenshot schaust, wo das Problem liegt – ich verstehe nicht ganz die Logik: Zuerst wird bei Kombination fett+kursiv wieder nur fett übernommen (siehe auch oben), dann wird aber aus kursiv im nächsten Halbsatz fett und wenn über „Graphics …“ fett im Original ist, wird fett nun gestrichen (vermutlich Invertierungsfehler)
- [x] Im nächsten Absatz wieder Invertierungsfehler: kursiv im Original wird zu fett in Import
- [x] Kombination Stichpunktliste mit Formatierungen im Original macht Probleme: Da Stichpukt bei Rocket.Chat nicht integriert sind, macht das Probleme, weil sich dadurch die importierte Formatierung verschiebt (Bei nummerierter Liste unten alles i.O., bis auf genannten Fehler Invertierung kursiv wird zu fett bei 2.) Kannst du da bitte nochmal schaun, was du machen kannst? Warum oben aus einem Stichpunkt eine 1. wird, erschließt sich mir auch nicht.
- [x] Formatierungsfehler in Test-Fall 4: (Ich glaube, dass das hier wirklich ein extrem Formatierungsfall für verkettete Formatierungen ist, der selten vorkommt. Wenn das zu aufwendig ist, dann können wir damit leben für den Import)

**Comment by simonline** [comment]
@michaelflohr Ich hab die Formatierung jetzt nochmals so gut wie möglich korrigiert. Alle Fehler konnte ich leider nicht beseitigen, aber schau mal ob es so reicht.

**Comment by ghost** [comment]
Ok, passt. Gibt noch Fehler, aber das sind seltene Fälle und für Import unerheblich. Damit kann jeder leben.
