### ISSUE TITLE
Formatierungsfehler Test-Fall 2

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#38]
Der Formatierungsfehler bei Überschriften in Nachrichtentext war zu vermuten, dass z.B. #-Angaben nicht übernommen werden, da in Rocket.Chat keine Formatierungsfunktion integriert. Ich denke, stört nicht so und geht ja auch nicht anders. Dagegen wäre schön, wenn du nochmal bei den anderen Formatierungsfehlern im unteren Screenshot schaust, wo das Problem liegt – ich verstehe nicht ganz die Logik: Zuerst wird bei Kombination fett+kursiv wieder nur fett übernommen (siehe auch oben), dann wird aber aus kursiv im nächsten Halbsatz fett und wenn über „Graphics …“ fett im Original ist, wird fett nun gestrichen (vermutlich Invertierungsfehler)

**Comment by ghost** [comment]
Ok
