### ISSUE TITLE
Anhänge

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#39]
Kleiner Hinweis zu den Anhängen: In Fall 3 sind die Anhänge jetzt dabei, allerdings mit zwei Einschränkungen:
- [ ] Reihenfolge: Da die Uhrzeit exakt gleich wie die dazugehörige Nachricht ist, sortiert das Rocket.Chat willkürlich. Manche Anhänge erscheinen daher leider bereits direkt vor der Nachricht.
- [ ] Upload-Limit: Ein Anhang war größer als 500MB und wurde deshalb nicht importiert. Soll ich die Maximalgröße für Uploads noch weiter hoch setzen?

**Comment by ghost** [comment]
Reihenfolge: Wenn möglich, für Import Anhänge immer Uhrzeit+5Sekunden angeben, damit es immer automatisch hinter Text ist.

Upload-Limit: Reicht auf 200MB. So können wir Riesendaten auch mal loswerden, die sicherlich eh immer schon mal abgespeichert wurden.
