### ISSUE TITLE
In forum-general Anzeige verstecken, dass Bot neue Nutzer hinzufügt

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#40]
Der plattform n-Bot fügt jetzt natürlich alle neuen plattform n-Mitglieder dem Kanal forum-general zu. @simonline Kann dieses Hinzufügen unsichtbar gemacht werden, sonst werden viele Nutzer*innen verschreckt oder dort wird niemals eine Diskussion oder ähnliches aufkommen, da jeden Tag gerade sehr viele neue nur dazukommen.

![grafik](https://user-images.githubusercontent.com/54441922/67748413-2a327b80-fa2b-11e9-8421-0d1532e2028e.png)

**Comment by simonline** [comment]
<img width="522" alt="Bildschirmfoto 2019-10-29 um 11 54 24" src="https://user-images.githubusercontent.com/190013/67762204-3297b000-fa45-11e9-9980-51f969c3de2a.png">

@michaelflohr Man kann die Einstellungen nach Typ deaktivieren. Allerdings gilt das dann für alle Kanäle, was meinst du?

**Comment by ghost** [comment]
Dann machen wir Benutzer hinzufügen desaktivieren. Machst du das @simonline ?

**Comment by simonline** [comment]
Ist erledigt.
