### ISSUE TITLE
Statistik plattform n: Integration Rocket.Chat in Statistik

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#42]
@simonline mit Bitte, mir den neuen Link zur Statistik zu senden. Geht mein alter Login?

**Comment by ghost** [comment]
@simonline Ich würde mich freuen, wenn du mir den Link zur neuen Statistikseite zusenden könntest und Rocket.Chat-Nutzung dort auch integrieren. Danke dir.

**Comment by simonline** [comment]
@michaelflohr Das ist jetzt erledigt, du solltest dafür in Matomo (stats.wechange.de) jetzt eine eigene Website (chat.plattform-n.org) sehen.
