### ISSUE TITLE
Verlinkung von Mailbenachrichtigung führt zu fehlender Navigationszeile

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#43]
[Ich hatte den Fehler beim Einführungstest schon mal notiert, aber nun ist er mir gerade wieder aufgefallen]

Wenn ich eine Mailbenachrichtigung erhalte, dass ich in Rocket.Chat eine Nachricht erhalten habe und dann auf den Link in der Mail gehe, dann öffnet sich Rocket.Chat normal, aber die Navigationszeile der plattform n fehlt. Das wäre aber wünschenswert.
@simonline

**Comment by simonline** [comment]
@michaelflohr Wir sind hier leider noch dran, melde mich im Lauf nächster Woche sobald das läuft.
