### ISSUE TITLE
Keine Aktualisierung neue Nachrichten in Handy-App - erst nach abmelden und neuanmelden

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#47]
Fehler mehrerer Nutzer mit eher älteren Smartphones. Sein Fall: "mein Betriebssystem ist Android 6.0.1 und die App-Version ist 3.5.1. Das es am Betriebssystem so liegt, könnte ich mir auch vorstellen, tatsächlich sind es vor allem Leute mit älteren Handys, die bei uns das Problem haben."

Beschreibung: Wenn man sich anmeldet werden alle Chats aktualisiert. Dann kann man die Chats zwar immer noch sehen und die Inhalte lesen, aber man empfängt keine neuen Nachrichten mehr. Tatsächlich werden immer noch die Nachrichten, die man liest, als gelesen markiert (und zwar sowohl auf dem Handy, als auch gleichzeitig wenn man sich über die plattform n im Borwser anmeldet), aber man empfängt auf dem Handy keine neuen Nachrichten mehr. Man muss sich dann in der App nochmal abmelden und wieder erneut anmelden, um neue Nachrichten zu empfangen.

Wenn die App neu geöffnet wird, wird angezeigt: "Your session is invalid. Pleas sign in again". Er musste sich im übrigen auch neu anmelden, damit eine Nachricht von ihm versendet werden konnte.

**Comment by ghost** [comment]
@simonline Kannst du dir das kurz anschauen und wenn du den Fehler bei der App siehst, diesen Fehler an Rocket.Chat melden? Haben die auch so ein Ticket-System?

**Comment by simonline** [comment]
@michaelflohr Das kann unmöglich an unserer Konfiguration liegen. Android 6 ist uralt, ich vermute die werden da wenig tun wollen. Aber du könntest den Fehler direkt bei Rocket.Chat melden:
- Forum: https://forums.rocket.chat/
- Support-Channel: https://open.rocket.chat/channel/support

**Comment by ghost** [comment]
@simonline Hilft dir diese Antwort auf meinen Post im Forum: https://forums.rocket.chat/t/sync-issues-problems-with-message-synchronization-between-the-application-and-the-server/5716/2

Please check “Settings” menu and see which “Server version:” it is reporting for the problematic server you are connected to.

In addition, it may help if you add https://open.rocket.chat to the app and see if you encounter the same problem with our latest version of the server.

**Comment by simonline** [comment]
@michaelflohr Ich kann das leider nicht testen. Jemand mit Android 6 müsste das mal wie empfohlen durchgehen und im Forum antworten.

Vor 7 Tagen ist übrigens die neue Rocket.Chat-Version 3.0 rausgekommen. Wir sind aktuell bei 2.4.9 und sollten dann in den nächsten Wochen mal updaten, sobald die Version stabil ist. Möglicherweise löst das auch den ein oder anderen Fehler.

**Comment by simonline** [comment]
@michaelflohr Könntest du mir außerdem die aktuellen Zugangsdaten zu konsoleh zukommen lassen? Ich würde gern bei nächster Gelegenheit eure Wordpress-Seite auf die WECHANGE-Server umziehen.
