### ISSUE TITLE
Globale Suche über alle Kanäle hinweg in Rocket.Chat aktivieren

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#48]
So wie bei wechange-Team-Rocket.Chat aktiviert wurde, sodass ich als Nutzer in Rocket.Chat der plattform n über alle Kanäle hinweg Infos suchen und finden kann.

**Comment by simonline** [comment]
Ist aktiviert. Das Feature ist allerdings noch in Beta und könnte die Plattform langsamer machen. Lass mich wissen, falls da eine spürbare Veränderung auftritt.
