### ISSUE TITLE
Live-Anzeige für neue Nachrichten in Rocket.Chat auf plattform n direkt

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#49]
Wunsch: Auf dem Briefumschlag (siehe Screenshot) der plattform n wird live angezeigt, wenn bei Rocket.Chat für den Nutzer eine neue Nachricht ungelesen bzw. eingegangen ist. Live-Anzeige mit Zahl für ungelesene Nachrichten bei Rocket.Chat.

![grafik](https://user-images.githubusercontent.com/54441922/71254600-c42beb80-232b-11ea-9daa-12850a6693cc.png)

**Comment by ghost** [comment]
@simonline Geht das? Wie viel Aufwand?

**Comment by simonline** [comment]
@michaelflohr Das ist möglich und auch bereits vorbereitet.

@saschan Lass uns den Restaufwand hierfür nächste Woche mal einschätzen.

**Comment by ghost** [comment]
Danke, freu mich auf eure Schätzung.

**Comment by simonline** [comment]
https://github.com/wechange-eg/cosinnus-message/blob/d6f64060201aea49ae0123b5b7212cdb4000181e/cosinnus_message/rocket_chat.py#L708

**Comment by saschasommer** [comment]
@saschan Meme für später: Api-backend: Rocket unreads bzw postman einbauen, und aus den context_processors sauber rausnehmen. Eigenes widgets für message-unreads parallel zu notifications.
```
from cosinnus_message.rocket_chat import RocketChatConnection
rocket = RocketChatConnection()
count = rocket.unread_messages()
```

**Comment by saschasommer** [comment]
@michaelflohr Habe jetzt mit Simon gesprochen, und ich würde das Ticket übernehmen. Wir haben uns vorgestellt, dass es das beste wäre, den Message unread-counter in dem Briefsymbol asynchron ladbar zu machen, und mit einem poll zu versehen, so dass auch bei einer geöffneten Seite die Nachrichtenzahl aktualisiert wird, wenn neue Nachrichten reinkommen (und nicht nur, nachdem man die Seite wechselt).

**Comment by michaelflohr** [comment]
@saschan : Danke, so nehme ich das mit deinem geschätzten Aufwand. Wann kannst du es umsetzen? Ist es gleich möglich noch bis z.B.  25.2., wenn ich da auch noch die Freischaltung des neuen Dashboards ansetzen würde.

**Comment by ghost** [comment]
@saschan Bitte sobald wie möglich umsetzen mit deiner Schätzung, die du mir per Rocket.Chat im Februar gesendet hast.
