### ISSUE TITLE
Standardeinstellung für "Sortier"-Funktion der Kanäle/Kommunikationen für alle Nutzer

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#50]
Ist es möglich, dass ich als Admin für alle Nutzer diese Sortier-Einstellung der Kanäle/Kommunikation als Standardeinstellung festlege (siehe Screenshot)? Ich finde, dass ist die sinnvollste und bestverständlichste Ansicht.

![grafik](https://user-images.githubusercontent.com/54441922/71254887-a0b57080-232c-11ea-9227-65a9d5ab277b.png)

**Comment by simonline** [comment]
Hab ich jetzt so eingestellt, bei meinem Benutzer wurde es direkt übernommen.

**Comment by ghost** [comment]
Vielen Dank für die schnelle Reaktion. Bei Verena war statt alphabetisch die Variante Aktivität noch markiert - alles andere hatte sie schon zuvor wie in meiner Standardeinstellung vorgegeben. D.h. ich kann jetzt leider nicht mit einem anderen Nutzer testen, ob das klappt, aber wenn's bei dir geklappt hat und du die globalen Einstellungen verändert hast, sollte das ja funktionieren.
