### ISSUE TITLE
Probleme bei Installation der Android-App

### ISSUE THREAD

**Issue by lucamarkus** [wechange-eg/rocket-chat#52]
ich habe in letzter Zeit mehrmals versucht die Android-App von RocketChat mit Plattform-N zu benutzen, jedoch komme ich nicht über die Einrichtung hinaus:

"Sobald ich "chat.plattform-n.org" als Serveradresse eingebe, komme ich ins nächste Fenster. Dort kann ich auch "Weitermachen mit Plattform-N Login" anklicken. Ich werde weitergeleitet und kann meine Login-Daten eingeben, doch dann entsteht eine Dauerschleife. Ich klicke auf Login und es kommt das Fenster, dass mich nach Autorisierung fragt. Ich bestätige die Autorisierung und lande wieder beim Login. Klicke ich erneut auf Login, lande ich wieder beim Authentifizieren.

Andere Personen aus unserer Gruppe haben das selbe Problem. Die Apple-Nutzer jedoch nicht."

**Comment by ghost** [comment]
Das wird ein allgemeines Problem mit Android bestimmt sein - siehe #47

**Comment by ghost** [comment]
@lucamarkus : Wichtig ist es, die Tickets hier Simon zuzuweisen ("Assignees" oben rechts)

**Comment by simonline** [comment]
@michaelflohr @lucamarkus Ich konnte das mit einem Android-Gerät reproduzieren und habe das Problem damit lösen können. Bitte probiert es jetzt nochmals, möglicherweise handelt es sich um verschiedene Probleme. Um das Problem weiter zu untersuchen bräuchte ich dann ggf. Direktkontakt und/oder den exakten Zugriffszeitpunkt.

**Comment by ghost** [comment]
Danke Simon. @lucamarkus kommunizierst du das bitte dem Nutzer und schließt dann das Ticket hier?
