### ISSUE TITLE
Mehrfachanmeldung zulassen (Browser, Desktop-App, Handy-App)

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#54]
Nutzer: "Mehrfache Anmeldung endlich zulassen, sodass ich mich nicht jedes Mal auf dem Handy neu anmelden muss."

Da das schon oft gemeldet wurde. Ich finde das auch sehr plausibel. Ist das umzustellen?

**Comment by simonline** [comment]
@michaelflohr Ich bin grad nochmals alle relevanten Einstellungen durchgegangen und hab auch bei einer kurzen Recherche nichts dazu finden können. Könntest du hierfür direkt bei Rocket.Chat nachhaken? Ich schaffe es leider gerade zeitlich nicht, hier zu vermitteln.

- Forum: https://forums.rocket.chat/
- Support-Channel: https://open.rocket.chat/channel/support

**Comment by ghost** [comment]
Das ist die Antwort aus dem Forum: https://forums.rocket.chat/t/allow-multiple-logins-browser-desktop-app-mobile-app/5877/4

 Check with your server administrator.

This is NOT the default behaviour :
but the problem is that when you log in with e.g. mobile app, you are automatically logged out in browser and desktop app

You can leave your session logged in across all devices. Like Whatsapp or other messengers.

**Comment by ghost** [comment]
@simonline ich habe gerade durch Zufall mit Verena herausgefunden, dass bei Rocket.Chat der Thinkfarm (chat.thinkfarm.org) die gleichzeitige Anmeldung möglich ist und sich dort nicht automatisch ausgeloggt wird zum Beispiel im Handy. D.h. es muss an den Einstellungen bei uns liegen. Kannst du da bitte nachschauen oder irgendwie vergleichen, was bei uns anders sein könnte? Du kannst mit Aljoscha Kontakt aufnehmen - er weiß Bescheid +49 171 9252111

**Comment by ghost** [comment]
**Test Auslogging - passiert überall:**
1) Desktop-App eingeloggt -> dann einloggen im Browser: automatisches Ausloggen in Desktop-App
2) Desktop-App eingeloggt -> dann einloggen in Handy-App: automatisches Ausloggen in Desktop-App
3) Handy-App eingeloggt -> dann einloggen im Browser: automatisches Ausloggen in Handy-App
4) Handy-App eingeloggt -> dann einloggen in Desktop-App: automatisches Ausloggen in Handy-App
5) Browser eingeloggt -> dann einloggen Handy-App: automatisches Ausloggen in Browser
6) Browser eingeloggt -> dann einloggen Desktop-App: automatisches Ausloggen in Browser

Gerade Handy-App neu einloggen immer wieder ist super nervig, da 3 Felder durchzuklicken sind und jedes Mal die Server-URL (chat.plattform-n.org) neu eingetippt werden muss.

**Comment by simonline** [comment]
@michaelflohr Danke für den Hinweis mit der Thinkfarm und deine Tests. Ich hatte zwischenzeitliche die normale Anmeldung (E-Mailadresse + Passwort) aktiviert, damit klappt es einwandfrei auf mehreren Geräten. Es liegt also an der Oauth2-Authentifizierung. Ich schreibe das mal ins Forum.

Auch hier könnte sich das Problem möglicherweise mit einem Update auf die neueste Rocket.Chat-Version erledigen.

**Comment by ghost** [comment]
@simonline Danke für Ausschalten Pop-up-Fenster (#57 ). Leider hat sich damit Problem des automatischen Abmeldens noch nicht gelöst. Gibt es da eine andere Einstellung? Bzw. hast du ein Update auf die neuste Version von Rocket.Chat durchgeführt?

**Comment by ghost** [comment]
Notiz @simonline Umzug alle Tickets auf gitlab Sinnwerkstatt erfolgt.

**Comment by saschan** [comment]
Wurde bereits behoben: https://git.sinnwerkstatt.com/wechange/plattform-n/-/issues/494#note_72043

**Comment by saschasommer** [comment]
Dieser Fehler sollte bereits behoben worden sein.
