### ISSUE TITLE
Keine gesonderte Anmeldung bei Übergang zu Rocket.Chat

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#55]
Nutzer: "Die Integration in die Plattform verbessern, sodass keine gesonderte Anmeldung für den Chat notwendig ist."

Finde ich überdenkenswert. Spricht etwas für dich @simonline dagegen? Wenn man klar kommuniziert, dass mit Login auf plattform n auch gleichzeitig der Login auf Rocket.Chat verbunden ist, dann würde das meiner Meinung nach die UX verbessern.

**Comment by simonline** [comment]
Ich kenne keine technisch elegante Lösung hierfür. Möglicherweise lässt sich das über domainweite Cookies steuern, aber das geht sehr greift sehr tief in Rocket.Chat ein, was ich gern vermeiden würde. Rocket.Chat ist technisch betrachtet eine eigene Plattform, für die Anmeldung braucht es die entsprechende Aktion des Benutzers. Die aktuelle Lösung nutzt bereits OAuth2 ohne weitere Zugangsdaten.

**Comment by ghost** [comment]
Ok, verstehe ich gut. Aufwand finde ich auch überschaubar. Wenn Mehrfach-Anmeldung mal zugelassen werden können (siehe #54 ), dann passt das so.
