### ISSUE TITLE
Text Pop-up Übergang Plattform zu Rocket.Chat

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#56]
Anpassung des Textes im Pop-up-Fenster
![grafik](https://user-images.githubusercontent.com/54441922/75030425-5ffce380-54a4-11ea-94a2-7ec3e22e40e7.png)

Vorschlag (Deutsch):

[Überschrift] Direktnachrichten & Team-Chat per Rocket.Chat

[Text] Wir haben den Open Source-Messenger Rocket.Chat in die Plattform integriert! Schreibt private Nachrichten in Echtzeit an andere Nutzer_innen, in Projekten, Gruppen oder in selbst angelegten Kanälen – im Browser, per Smartphone- oder Desktop-App.

Übertritt zu Rocket.Chat.

[Buttons] Abbruch Zustimming

**Comment by simonline** [comment]
Popup jetzt ganz deaktiviert.
