### ISSUE TITLE
Herausnahme OAuth Pop-Up-Fenster bei Anmeldung

### ISSUE THREAD

**Issue by ghost** [wechange-eg/rocket-chat#57]
Bitte umsetzen: Fenster ist unnötig, da Nutzer schon mit Nutzungsbedingungen Rocket.Chat (siehe Screenshot) zustimmt. Damit sollte dann auch hoffentlich Problem des automatischen Ausloggens bei Wechsel zwischen Browser, Desktop-App und Handy-App gelöst sein.

![grafik](https://user-images.githubusercontent.com/54441922/78262007-410c5b00-7500-11ea-9374-f4d86e4a6c89.png)

**Comment by simonline** [comment]
Ist jetzt angepasst.
