### ISSUE TITLE
Mein Konto > Einstellungen

### ISSUE THREAD

**Issue by simonline** [wechange-eg/rocket-chat#8]
Was bedeutet „Global“? Da kann nichts eingetragen oder verändert werden. Daher bitte löschen, wenn es keinen Zweck hat.

![screenshot-5](https://user-images.githubusercontent.com/190013/63445396-8def6580-c438-11e9-8a4d-1df849c2a3ff.png)

**Comment by ghost** [comment]
Bleibt drin, da wir nicht zu viel unsichtbar machen wollen, was von Rocket.Chat vorgesehen ist.
